name: Build Windows

on:
  repository_dispatch:
    types: [build-windows]
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository'
        required: true
        default: 'minorityedge/crypto_web'
      ref:
        description: 'Branch or commit'
        required: true
        default: 'main'
      channel:
        description: 'Release channel'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - dev

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo || github.event.inputs.source_repo }}
          ref: ${{ github.event.client_payload.ref || github.event.inputs.ref }}
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set release channel
        id: channel
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            echo "channel=${{ github.event.inputs.channel }}" >> $env:GITHUB_OUTPUT
          } elseif ("${{ github.event_name }}" -eq "repository_dispatch") {
            echo "channel=${{ github.event.client_payload.channel }}" >> $env:GITHUB_OUTPUT
          } elseif ("${{ github.event.client_payload.ref || github.event.inputs.ref }}" -eq "refs/heads/main") {
            echo "channel=latest" >> $env:GITHUB_OUTPUT
          } else {
            echo "channel=dev" >> $env:GITHUB_OUTPUT
          }
        shell: powershell

      - name: Update version for dev channel
        if: steps.channel.outputs.channel == 'dev'
        run: npm version prerelease --preid=dev --no-git-tag-version

      - name: Build Electron app
        run: npm run build:electron
        env:
          UPDATE_CHANNEL: ${{ steps.channel.outputs.channel }}

      - name: Create channel-specific update files
        run: |
          New-Item -ItemType Directory -Force -Path dist
          if ("${{ steps.channel.outputs.channel }}" -eq "dev") {
            if (Test-Path "dist/dev.yml") {
              Write-Output "Found existing dev.yml"
            } else {
              Write-Output "Creating dev.yml manually"
              @"
          provider: github
          owner: minorityedge
          repo: minorityedge-releases
          updaterCacheDirName: minority-edge-updater
          "@ | Out-File -FilePath "dist/dev.yml" -Encoding utf8
            }
            Write-Output "Created dev.yml"
            Get-ChildItem dist/*.yml
          } else {
            if (Test-Path "dist/latest.yml") {
              Write-Output "Found existing latest.yml"
            } else {
              Write-Output "Creating latest.yml manually"
              @"
          provider: github
          owner: minorityedge
          repo: minorityedge-releases
          updaterCacheDirName: minority-edge-updater
          "@ | Out-File -FilePath "dist/latest.yml" -Encoding utf8
            }
            Write-Output "Created latest.yml"
            Get-ChildItem dist/*.yml
          }
        shell: powershell

      - name: Build and Publish Windows to Public Repository
        run: npm run electron:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE_CHANNEL: ${{ steps.channel.outputs.channel }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
